SRC = abi
all:
	pdflatex --file-line-error-style $(SRC).tex
	pdflatex --file-line-error-style $(SRC).tex
	#bibtex $(SRC).aux
	#bibtex $(SRC).aux
	#pdflatex --file-line-error-style $(SRC).tex
	#pdflatex --file-line-error-style $(SRC).tex
